### ISSUE TITLE
Infobox not disappearing

### ISSUE THREAD

**Issue by Intecpsp** [geel9/runelite-hunter-rumours#57] opened 2024-07-03 12:10 UTC
My infobox doesn't seem to be disappearing after 5 minutes like the config says it should. I haven't done rumors in a while and I'm wondering if this may be the cause of the box not disappearing (may be triggered 5 minutes after the last rumor, but not after 5 minutes of no rumors).

**Comment by DapperMickie** [comment] 2024-07-03 12:19
I'll look into this

**Comment by Intecpsp** [comment] 2024-07-03 12:26
Not quite sure what happened, but I reset the plugin, and toggled force show on and off again, then it expired. I relaunched the app to see if the infobox expired on a fresh instance, and it did. So looks like I had a bad config?

**Comment by DapperMickie** [comment] 2024-07-03 12:28
My own client still has this same issue so I've reopened to investigate

**Comment by Intecpsp** [comment] 2024-07-03 12:30
Just to confirm, the map locations rolled off as well for me after the time out. I did not mess with the map force show option, only the info box.

**Comment by DapperMickie** [comment] 2024-07-03 12:53
Can't reproduce this behavior anymore after changing the configs. I'll close this for now, but keep an eye out for it whenever I work on the rest of the plugin.

**Closed by DapperMickie** 2024-07-03 12:53 UTC
