### ISSUE TITLE
Caught value not resetting after each rumour

### ISSUE THREAD

**Issue by TomSparto** [geel9/runelite-hunter-rumours#35] opened 2024-05-23 02:58 UTC
As the title states. I like the addition of this new feature, but the caught value seems to carry over between each rumour. 

- Restarting the game does not seem to reset this value.
- Getting assigned a new task from a different rumour master does not reset this value either.

The value was reset at one point for me, but I'm unsure what criteria was met.

**Comment by TomSparto** [comment] 2024-05-23 06:08
Just for reference, after a play session of rumours I have 517/30 for my next rumour lol
![image](https://github.com/geel9/runelite-hunter-rumours/assets/84285661/4127bd34-ed5d-4d6e-a6ae-d982e000fb9f)

**Comment by DapperMickie** [comment] 2024-05-23 09:09
@TomSparto Thanks for the feedback I'm looking into it right now

**Comment by DapperMickie** [comment] 2024-05-23 09:39
@TomSparto For now I'd recommend using the `::resetrumours` command (just type that in chat), that will reset the plugin's state. And if you manage to reproduce this error, please let us know in here!

**Comment by evilgenious448** [comment] 2024-05-23 15:06
Mine is completely scuffed. Ended up with -120 lmao.

Here's what I did:

1. Get task from Teco (Expert) - He assigns Red Chin
2. I catch 51 red chins and get the rare part
3. I go back to Teco (Expert) and get another rumor - Red Chins again
4. Plugin now says I need 49 to catch
5. I caught like 70 and it went to -21.
6. I handed in the Chin piece and got Dashing Kebbit. It now says -102 LMFAO

**Comment by TomSparto** [comment] 2024-05-23 16:49
@DapperMickie Here is what I tried today.

1. I used the `::resetrumours` in the chat. This did reset all my rumour data as expected.
2. I talked to Gilman, Ornus, and Cervus to update my UI with all relevant rumours.
3. I am currently tasked by Ornus to hunt Sabre-toothed Kebbit
4. I caught 22/30 of these kebbit to complete this rumour
5. I returned to Ornus and used left click to claim my reward.
6. From there I continued through the chat until he asked me if I wanted another rumour which I selected yes.
7. Now I am assigned spotted Kebbit and the caught value says 22/20 when mousing over the infobox for spotted kebbit

**Comment by DapperMickie** [comment] 2024-05-23 17:04
> @DapperMickie Here is what I tried today.
> 
> 1. I used the `::resetrumours` in the chat. This did reset all my rumour data as expected.
> 2. I talked to Gilman, Ornus, and Cervus to update my UI with all relevant rumours.
> 3. I am currently tasked by Ornus to hunt Sabre-toothed Kebbit
> 4. I caught 22/30 of these kebbit to complete this rumour
> 5. I returned to Ornus and used left click to claim my reward.
> 6. From there I continued through the chat until he asked me if I wanted another rumour which I selected yes.
> 7. Now I am assigned spotted Kebbit and the caught value says 22/20 when mousing over the infobox for spotted kebbit
> 
> If I had the `Show catches remaining` setting enabled, then this displays a `-2`. I turned this setting off for now, because of this reason. However, this is the same behavior as described by @evilgenious448 

If you're still doing rumours, could you record the part when you get a new task (using smth like gyazo). I still havent been able to reproduce this bug on my end.

**Comment by TomSparto** [comment] 2024-05-23 17:09
I have only been consistently doing Ornus since I noticed it consistently not working. When I mentioned in my first response that it successfully reset I was doing Gilman and switching to Ornus. Getting a new rumour from Gilman could be working correctly. However, I would need to test that more. I need to switch to Cervus now, so maybe doing a rumour from him will successfully reset the value. I will let you know if that provides any better visibility.

**Comment by DapperMickie** [comment] 2024-05-23 17:30
@TomSparto Well that's kinda annoying because I consistently can't reproduce this bug :(. I will look into this a bit more later today. If you'd be willing to screenshot messages received whenever you give the item to the guild hunters, I'd greatly appreciate that.

**Comment by TomSparto** [comment] 2024-05-23 17:32
@DapperMickie if you are open to the idea, you can add me on discord `tomsparto` and we can attempt to schedule a screen share session where I can demo the issue live for you.

**Comment by DapperMickie** [comment] 2024-05-23 18:16
We found the issue, right now, either swap left click for the masters with "Rumour" or right-click "rumour" whenever you finish your rumours!

**Comment by DapperMickie** [comment] 2024-05-23 19:56
Will be fixed in this update: https://github.com/runelite/plugin-hub/pull/6062

**Closed** 2024-05-23 20:32 UTC
