### ISSUE TITLE
Number of Animals Caught Incorrect

### ISSUE THREAD

**Issue by coopermor** [geel9/runelite-hunter-rumours#42] opened 2024-05-28 23:59 UTC
The number of animals caught does not seem to be reset when getting a task. I just got a grey chinchompa task for the first time since starting the client. It says I have caught 518/100 however I have not caught any since being assigned the rumour.
![image](https://github.com/geel9/runelite-hunter-rumours/assets/8049699/dbca16eb-3e54-4cb1-886d-9fa23a6b77bd)

**Comment by coopermor** [comment] 2024-05-29 02:46
Now that I've been doing adept rumours this seems to be working properly. Maybe this is only a bug using novice rumours?

**Comment by DapperMickie** [comment] 2024-05-29 03:14
This is a duplicate of https://github.com/geel9/runelite-hunter-rumours/issues/40 and has been fixed. We're still working on some other stuff before updating the plugin.

**Closed by DapperMickie** 2024-05-29 03:14 UTC
