### ISSUE TITLE
Caught Creatures counter doesn't always reset to 0 on starting a new rumor

### ISSUE THREAD

**Issue by Peffern** [geel9/runelite-hunter-rumours#54] opened 2024-06-16 23:29 UTC
Sometimes (I don't have a reliable way to reproduce yet but if I find one I'll post it here), when turning in a rumor, the counter of how many creatures have been caught doesn't reset to 0. This means that the next rumor will have show the wrong number remaining, and sometimes even by negative. I looked at the code and it's probably something with the chat parser, but I'm not familiar enough with the RL API to know what. Are the chat messages case sensitive? That could be it.
In case it matters, I am using Gilman. 

Alternatively, if tracking this down isn't something you want to do, could you either add a button in the config panel to reset it to 0, or add an option to make checking the whistle reset it to 0? That would at least allow for manual intervention, as-is there's no way to fix it without closing RL and editing the profile file.

I'll take a closer look later when I can.

**Comment by DapperMickie** [comment] 2024-06-16 23:47
This has been fixed and will be added in: https://github.com/runelite/plugin-hub/pull/6132 
I'll keep this open until the PR has been accepted by RL because this is a duplicate of multiple other closed issues.

**Comment by DapperMickie** [comment] 2024-06-23 08:47
The PR has been accepted, restart your client to get the latest update.

**Closed by DapperMickie** 2024-06-23 08:47 UTC
